### PR TITLE
Add distance transform to watershed

### PR DESCRIPTION
**Pull request by jamesyan-git**
Prior watershed split implementation did not work for 2D as it assumed 3D for connectivity. This has been changed to use a distance transform that works for nD. Tests to follow shortly

### CODE REVIEW

**Comment by jni** [comment]
:heart: lovely! :blush:

**Comment by jamesyan-git** [comment]
@jni Hey Juan, I have some tests for the new watershed split

**Comment by GenevieveBuckley** [comment]
Good, the current behaviour annoyed me. With the distance transform it should be much nicer!

**Comment by jni** [comment]
Woot woot! Thank you @jamesyan-git for the great implementation and great tests (!), and @GenevieveBuckley for the prod! :blush:

**Pull request merged**
